# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a81e97fb46d933d15e07ba2f1f573b097d90853956afe02ed85d57736c0468bf7638efa51b5c707f0e71859b3392628156a361d3dcb89b03a4fe2f1b683a996

test:
  secret_key_base: 28b960495544a40e9778946b72392a33ace831b55486a71642eaf0546c0abe298d07476cd114aa99b40256567c4fcebcb85790509ddf5eab28f82d068500248a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
